# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ciompin/PairwiseEP/master_thesis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ciompin/PairwiseEP/master_thesis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ciompin/PairwiseEP/master_thesis/CMakeFiles /home/ciompin/PairwiseEP/master_thesis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ciompin/PairwiseEP/master_thesis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Thesis

# Build rule for target.
Thesis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Thesis
.PHONY : Thesis

# fast build rule for target.
Thesis/fast:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/build
.PHONY : Thesis/fast

#=============================================================================
# Target rules for targets named ep_sim

# Build rule for target.
ep_sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ep_sim
.PHONY : ep_sim

# fast build rule for target.
ep_sim/fast:
	$(MAKE) -f CMakeFiles/ep_sim.dir/build.make CMakeFiles/ep_sim.dir/build
.PHONY : ep_sim/fast

#=============================================================================
# Target rules for targets named ppv_compare

# Build rule for target.
ppv_compare: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppv_compare
.PHONY : ppv_compare

# fast build rule for target.
ppv_compare/fast:
	$(MAKE) -f CMakeFiles/ppv_compare.dir/build.make CMakeFiles/ppv_compare.dir/build
.PHONY : ppv_compare/fast

#=============================================================================
# Target rules for targets named ppv_plotter

# Build rule for target.
ppv_plotter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppv_plotter
.PHONY : ppv_plotter

# fast build rule for target.
ppv_plotter/fast:
	$(MAKE) -f CMakeFiles/ppv_plotter.dir/build.make CMakeFiles/ppv_plotter.dir/build
.PHONY : ppv_plotter/fast

#=============================================================================
# Target rules for targets named real_seq

# Build rule for target.
real_seq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 real_seq
.PHONY : real_seq

# fast build rule for target.
real_seq/fast:
	$(MAKE) -f CMakeFiles/real_seq.dir/build.make CMakeFiles/real_seq.dir/build
.PHONY : real_seq/fast

#=============================================================================
# Target rules for targets named seq_splitter

# Build rule for target.
seq_splitter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 seq_splitter
.PHONY : seq_splitter

# fast build rule for target.
seq_splitter/fast:
	$(MAKE) -f CMakeFiles/seq_splitter.dir/build.make CMakeFiles/seq_splitter.dir/build
.PHONY : seq_splitter/fast

src/entropies.o: src/entropies.cpp.o
.PHONY : src/entropies.o

# target to build an object file
src/entropies.cpp.o:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/entropies.cpp.o
.PHONY : src/entropies.cpp.o

src/entropies.i: src/entropies.cpp.i
.PHONY : src/entropies.i

# target to preprocess a source file
src/entropies.cpp.i:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/entropies.cpp.i
.PHONY : src/entropies.cpp.i

src/entropies.s: src/entropies.cpp.s
.PHONY : src/entropies.s

# target to generate assembly for a file
src/entropies.cpp.s:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/entropies.cpp.s
.PHONY : src/entropies.cpp.s

src/ep_sim.o: src/ep_sim.cpp.o
.PHONY : src/ep_sim.o

# target to build an object file
src/ep_sim.cpp.o:
	$(MAKE) -f CMakeFiles/ep_sim.dir/build.make CMakeFiles/ep_sim.dir/src/ep_sim.cpp.o
.PHONY : src/ep_sim.cpp.o

src/ep_sim.i: src/ep_sim.cpp.i
.PHONY : src/ep_sim.i

# target to preprocess a source file
src/ep_sim.cpp.i:
	$(MAKE) -f CMakeFiles/ep_sim.dir/build.make CMakeFiles/ep_sim.dir/src/ep_sim.cpp.i
.PHONY : src/ep_sim.cpp.i

src/ep_sim.s: src/ep_sim.cpp.s
.PHONY : src/ep_sim.s

# target to generate assembly for a file
src/ep_sim.cpp.s:
	$(MAKE) -f CMakeFiles/ep_sim.dir/build.make CMakeFiles/ep_sim.dir/src/ep_sim.cpp.s
.PHONY : src/ep_sim.cpp.s

src/kernel_gen.o: src/kernel_gen.cpp.o
.PHONY : src/kernel_gen.o

# target to build an object file
src/kernel_gen.cpp.o:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/kernel_gen.cpp.o
.PHONY : src/kernel_gen.cpp.o

src/kernel_gen.i: src/kernel_gen.cpp.i
.PHONY : src/kernel_gen.i

# target to preprocess a source file
src/kernel_gen.cpp.i:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/kernel_gen.cpp.i
.PHONY : src/kernel_gen.cpp.i

src/kernel_gen.s: src/kernel_gen.cpp.s
.PHONY : src/kernel_gen.s

# target to generate assembly for a file
src/kernel_gen.cpp.s:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/kernel_gen.cpp.s
.PHONY : src/kernel_gen.cpp.s

src/ppv_compare.o: src/ppv_compare.cpp.o
.PHONY : src/ppv_compare.o

# target to build an object file
src/ppv_compare.cpp.o:
	$(MAKE) -f CMakeFiles/ppv_compare.dir/build.make CMakeFiles/ppv_compare.dir/src/ppv_compare.cpp.o
.PHONY : src/ppv_compare.cpp.o

src/ppv_compare.i: src/ppv_compare.cpp.i
.PHONY : src/ppv_compare.i

# target to preprocess a source file
src/ppv_compare.cpp.i:
	$(MAKE) -f CMakeFiles/ppv_compare.dir/build.make CMakeFiles/ppv_compare.dir/src/ppv_compare.cpp.i
.PHONY : src/ppv_compare.cpp.i

src/ppv_compare.s: src/ppv_compare.cpp.s
.PHONY : src/ppv_compare.s

# target to generate assembly for a file
src/ppv_compare.cpp.s:
	$(MAKE) -f CMakeFiles/ppv_compare.dir/build.make CMakeFiles/ppv_compare.dir/src/ppv_compare.cpp.s
.PHONY : src/ppv_compare.cpp.s

src/ppv_plotter.o: src/ppv_plotter.cpp.o
.PHONY : src/ppv_plotter.o

# target to build an object file
src/ppv_plotter.cpp.o:
	$(MAKE) -f CMakeFiles/ppv_plotter.dir/build.make CMakeFiles/ppv_plotter.dir/src/ppv_plotter.cpp.o
.PHONY : src/ppv_plotter.cpp.o

src/ppv_plotter.i: src/ppv_plotter.cpp.i
.PHONY : src/ppv_plotter.i

# target to preprocess a source file
src/ppv_plotter.cpp.i:
	$(MAKE) -f CMakeFiles/ppv_plotter.dir/build.make CMakeFiles/ppv_plotter.dir/src/ppv_plotter.cpp.i
.PHONY : src/ppv_plotter.cpp.i

src/ppv_plotter.s: src/ppv_plotter.cpp.s
.PHONY : src/ppv_plotter.s

# target to generate assembly for a file
src/ppv_plotter.cpp.s:
	$(MAKE) -f CMakeFiles/ppv_plotter.dir/build.make CMakeFiles/ppv_plotter.dir/src/ppv_plotter.cpp.s
.PHONY : src/ppv_plotter.cpp.s

src/real_seq.o: src/real_seq.cpp.o
.PHONY : src/real_seq.o

# target to build an object file
src/real_seq.cpp.o:
	$(MAKE) -f CMakeFiles/real_seq.dir/build.make CMakeFiles/real_seq.dir/src/real_seq.cpp.o
.PHONY : src/real_seq.cpp.o

src/real_seq.i: src/real_seq.cpp.i
.PHONY : src/real_seq.i

# target to preprocess a source file
src/real_seq.cpp.i:
	$(MAKE) -f CMakeFiles/real_seq.dir/build.make CMakeFiles/real_seq.dir/src/real_seq.cpp.i
.PHONY : src/real_seq.cpp.i

src/real_seq.s: src/real_seq.cpp.s
.PHONY : src/real_seq.s

# target to generate assembly for a file
src/real_seq.cpp.s:
	$(MAKE) -f CMakeFiles/real_seq.dir/build.make CMakeFiles/real_seq.dir/src/real_seq.cpp.s
.PHONY : src/real_seq.cpp.s

src/score_filler.o: src/score_filler.cpp.o
.PHONY : src/score_filler.o

# target to build an object file
src/score_filler.cpp.o:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/score_filler.cpp.o
.PHONY : src/score_filler.cpp.o

src/score_filler.i: src/score_filler.cpp.i
.PHONY : src/score_filler.i

# target to preprocess a source file
src/score_filler.cpp.i:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/score_filler.cpp.i
.PHONY : src/score_filler.cpp.i

src/score_filler.s: src/score_filler.cpp.s
.PHONY : src/score_filler.s

# target to generate assembly for a file
src/score_filler.cpp.s:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/score_filler.cpp.s
.PHONY : src/score_filler.cpp.s

src/seq_splitter.o: src/seq_splitter.cpp.o
.PHONY : src/seq_splitter.o

# target to build an object file
src/seq_splitter.cpp.o:
	$(MAKE) -f CMakeFiles/seq_splitter.dir/build.make CMakeFiles/seq_splitter.dir/src/seq_splitter.cpp.o
.PHONY : src/seq_splitter.cpp.o

src/seq_splitter.i: src/seq_splitter.cpp.i
.PHONY : src/seq_splitter.i

# target to preprocess a source file
src/seq_splitter.cpp.i:
	$(MAKE) -f CMakeFiles/seq_splitter.dir/build.make CMakeFiles/seq_splitter.dir/src/seq_splitter.cpp.i
.PHONY : src/seq_splitter.cpp.i

src/seq_splitter.s: src/seq_splitter.cpp.s
.PHONY : src/seq_splitter.s

# target to generate assembly for a file
src/seq_splitter.cpp.s:
	$(MAKE) -f CMakeFiles/seq_splitter.dir/build.make CMakeFiles/seq_splitter.dir/src/seq_splitter.cpp.s
.PHONY : src/seq_splitter.cpp.s

src/stat_models.o: src/stat_models.cpp.o
.PHONY : src/stat_models.o

# target to build an object file
src/stat_models.cpp.o:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/stat_models.cpp.o
.PHONY : src/stat_models.cpp.o

src/stat_models.i: src/stat_models.cpp.i
.PHONY : src/stat_models.i

# target to preprocess a source file
src/stat_models.cpp.i:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/stat_models.cpp.i
.PHONY : src/stat_models.cpp.i

src/stat_models.s: src/stat_models.cpp.s
.PHONY : src/stat_models.s

# target to generate assembly for a file
src/stat_models.cpp.s:
	$(MAKE) -f CMakeFiles/Thesis.dir/build.make CMakeFiles/Thesis.dir/src/stat_models.cpp.s
.PHONY : src/stat_models.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Thesis"
	@echo "... edit_cache"
	@echo "... ep_sim"
	@echo "... ppv_compare"
	@echo "... ppv_plotter"
	@echo "... real_seq"
	@echo "... rebuild_cache"
	@echo "... seq_splitter"
	@echo "... src/entropies.o"
	@echo "... src/entropies.i"
	@echo "... src/entropies.s"
	@echo "... src/ep_sim.o"
	@echo "... src/ep_sim.i"
	@echo "... src/ep_sim.s"
	@echo "... src/kernel_gen.o"
	@echo "... src/kernel_gen.i"
	@echo "... src/kernel_gen.s"
	@echo "... src/ppv_compare.o"
	@echo "... src/ppv_compare.i"
	@echo "... src/ppv_compare.s"
	@echo "... src/ppv_plotter.o"
	@echo "... src/ppv_plotter.i"
	@echo "... src/ppv_plotter.s"
	@echo "... src/real_seq.o"
	@echo "... src/real_seq.i"
	@echo "... src/real_seq.s"
	@echo "... src/score_filler.o"
	@echo "... src/score_filler.i"
	@echo "... src/score_filler.s"
	@echo "... src/seq_splitter.o"
	@echo "... src/seq_splitter.i"
	@echo "... src/seq_splitter.s"
	@echo "... src/stat_models.o"
	@echo "... src/stat_models.i"
	@echo "... src/stat_models.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

